# -*- mode: ruby -*-
# vi: set ft=ruby :

# Global Configuration
Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-16.04"
    config.vm.hostname = "elaignel"

    # Provider Configuration
    config.vm.provider "virtualbox" do |vb|
     vb.cpus = "12"
     vb.memory = "8000"

    # Network Configuration
    config.vm.network "forwarded_port", guest: 3128, host: 3128, host_ip: "127.0.0.1"

    # Provisioning script
    config.vm.provision "shell", path: "startup.sh"

   end
end
