# -*- mode: ruby -*-
# vi: set ft=ruby :

# Global configuration
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = "1024"
  end

  # Server Configuration
  config.vm.define "server" do |server|

    # Network Configuration
    server.vm.hostname = "elaignelS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Provisioning script
    server.vm.provision "shell", path: "scripts/server_bootstrap.sh"
  end

  # Server Worker Configuration
  config.vm.define "serverWorker" do |serverWorker|

    # Network Configuration
    serverWorker.vm.hostname = "elaignelSW"
    serverWorker.vm.network "private_network", ip: "192.168.56.111"

    # Provisioning script
    serverWorker.vm.provision "shell", path: "scripts/server_worker_bootstrap.sh"
  end
end
